# FluxRT —— Rust/C 集成与构建档选择（被生成的 CMakeLists.txt include）。
# FluxRT - Rust/C integration and build-profile selection (included by the generated
# CMakeLists.txt).
#
# 为什么单独一个文件 / Why this is a separate file:
#   CMakeLists.txt 由 `scons --target=cmake` 从 SConscript 与 Kconfig 生成，每次
#   regenerate 都会被覆盖，因此任何手写内容都必须放在一个生成器"只 include、不重写"
#   的文件里——就是本文件。
#   CMakeLists.txt is generated by `scons --target=cmake` from the SConscript files and
#   Kconfig and is overwritten on every regeneration, so anything hand-written has to
#   live in a file the generator includes but never rewrites: this one.
#
# 职责 / Responsibility:
#   - 定义并校验 FLUXRT_BUILD_PROFILE 与 FLUXRT_RUST_OPT_LEVEL 两个 cache 变量；
#   - 用 add_custom_command 构建 Rust 静态库，并按 rtconfig.h 决定是否带 CORDIC 特性；
#   - 修正 RT-Thread 生成器写下的 Rust 静态库链接目录，并补上 ELF 对静态库的
#     LINK_DEPENDS，使"只改 Rust"也能触发重链接；
#   - 用 -O3 单独编译实时硬件适配层（rtt_FOC），并注入档位宏定义。
#   - Defines and validates the two cache variables; builds the Rust static library with
#     add_custom_command, selecting the CORDIC feature from rtconfig.h; corrects the Rust
#     link directory that the RT-Thread generator wrote and adds the ELF's LINK_DEPENDS on
#     the archive so a Rust-only change relinks; compiles the realtime hardware adapter
#     (rtt_FOC) with -O3 and injects the profile defines.
#
# Flash 预算 / Flash budget:
#   STM32G431RBT6 的 128 KiB Flash 是本工程最紧张的资源，比 32 KiB SRAM 紧得多。所以
#   Rust 优化等级与构建档都是实测结果：`s` 相对 `3` 省约 5 KB Flash 而完整 ISR WCET
#   只涨约 2%；`z` 再省 800 B 却让 WCET 涨约 7%。切换 Profile 或 RustOptLevel 后必须
#   重新记录 fluxrt.bin 的 SHA-256、text/data/bss 与板端 WCET，见 docs/构建档与优化等级.md。
#   The STM32G431RBT6's 128 KiB of Flash is the tightest resource in this project, much
#   tighter than the 32 KiB of SRAM. The Rust opt-level and the profile are therefore
#   measured outcomes: `s` saves about 5 KB of Flash over `3` while the full ISR WCET
#   grows about 2%; `z` saves another 800 B and costs about 7% more WCET. After changing
#   Profile or RustOptLevel the fluxrt.bin SHA-256, text/data/bss and on-board WCET must
#   be re-recorded; see docs/构建档与优化等级.md.
#
# 参考 / Reference: docs/构建档与优化等级.md, docs/架构与安全边界.md

find_program(CARGO_EXECUTABLE cargo REQUIRED)

# 档位与优化等级作为 cache 变量，便于 build.ps1 用 -D 传入并在 CMakeCache.txt 里留痕；
# build.ps1 -BuildOnly 会读回这两个值，防止把一种配置的固件当成另一种。
# Profile and opt-level are cache variables so build.ps1 can pass them with -D and they
# leave a trace in CMakeCache.txt; build.ps1 -BuildOnly reads them back to prevent one
# configuration being mistaken for another.
set(FLUXRT_BUILD_PROFILE "diagnostic" CACHE STRING
    "FluxRT firmware profile: diagnostic, calibration, or production")
set_property(CACHE FLUXRT_BUILD_PROFILE PROPERTY STRINGS diagnostic calibration production)
set(FLUXRT_RUST_OPT_LEVEL "s" CACHE STRING
    "Rust release optimization level: 3, s, or z")
set_property(CACHE FLUXRT_RUST_OPT_LEVEL PROPERTY STRINGS 3 s z)

# 在这里再校验一次取值：CMake 的 cache 可以被 -D 绕过 ValidateSet，非法档位必须硬失败，
# 否则会静默产生一个不属于任何已定义档位的镜像。
# The values are validated again here because a cache entry can be set with -D, bypassing
# the ValidateSet in build.ps1; an invalid profile must fail hard rather than silently
# produce an image that belongs to no defined profile.
if(NOT FLUXRT_BUILD_PROFILE MATCHES "^(diagnostic|calibration|production)$")
    message(FATAL_ERROR "FLUXRT_BUILD_PROFILE must be diagnostic, calibration, or production")
endif()
if(NOT FLUXRT_RUST_OPT_LEVEL MATCHES "^(3|s|z)$")
    message(FATAL_ERROR "FLUXRT_RUST_OPT_LEVEL must be 3, s, or z")
endif()

# 每个档位和优化等级使用独立的 Rust target 目录，避免不同构建复用同一个
# libfoc_rt_bridge.a；Diagnostic 可带额外 Rust feature，因此仅按优化等级隔离不够。
# 复用的后果是链接到与本次记录不符的静态库，Flash 与 WCET 数据随之失效。
# Every profile/opt-level pair gets its own Rust target directory. Diagnostic may
# enable extra Rust features, so opt-level isolation alone is insufficient.
set(FOC_RUST_TARGET "thumbv7em-none-eabihf")
set(FOC_RUST_DIR "${CMAKE_SOURCE_DIR}/rust")
set(FOC_RUST_TARGET_DIR
    "${CMAKE_SOURCE_DIR}/build/rust-target-${FLUXRT_BUILD_PROFILE}-${FLUXRT_RUST_OPT_LEVEL}")
set(FOC_RUST_ARCHIVE
    "${FOC_RUST_TARGET_DIR}/${FOC_RUST_TARGET}/release/libfoc_rt_bridge.a")
# rtconfig.h 由 SCons 从 Kconfig 生成，CORDIC 开关与 FOC_ISR_TIMING_PROBE 都在里面；
# 把它加入 configure 依赖，使 Kconfig 改动后 CMake 会重新配置。
# rtconfig.h is generated by SCons from Kconfig and carries the CORDIC switch and
# FOC_ISR_TIMING_PROBE; making it a configure dependency re-runs CMake after a Kconfig
# change.
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
    "${CMAKE_SOURCE_DIR}/rtconfig.h")

# CORDIC 后端来自 Kconfig（FOC_MATH_BACKEND_STM32G4_CORDIC），这里读生成后的 rtconfig.h
# 决定是否给 Rust 加 --features stm32g4-cordic。两种后端都必须能编过：CORDIC 只是加速，
# Rust 侧对每个加速操作都有 CPU 回退，因此关掉它不会改变算法行为，只影响周期数。
# The CORDIC backend comes from Kconfig (FOC_MATH_BACKEND_STM32G4_CORDIC); the generated
# rtconfig.h decides whether Rust is built with --features stm32g4-cordic. Both backends
# must compile: CORDIC is an accelerator only, every accelerated operation has a CPU
# fallback on the Rust side, so disabling it changes cycle counts, not algorithms.
file(STRINGS "${CMAKE_SOURCE_DIR}/rtconfig.h" FOC_CORDIC_CONFIG_LINE
    REGEX "^#define FOC_MATH_BACKEND_STM32G4_CORDIC$")
set(FOC_RUST_FEATURE_ARGS)
if(FOC_CORDIC_CONFIG_LINE)
    list(APPEND FOC_RUST_FEATURE_ARGS --features stm32g4-cordic)
    message(STATUS "FOC math backend: STM32G4 CORDIC + FPU with automatic CPU fallback")
else()
    message(STATUS "FOC math backend: portable CPU")
endif()

# CPU 快速近似的导出与实时选择都只进入 Diagnostic。即使旧 .config 遗留开关，
# Production 也不会把候选 feature 传给 Rust，因此量产路径不能被诊断配置误改。
# Fast-approximation exports and realtime selection are Diagnostic-only. A stale
# switch in .config cannot affect Production because no candidate feature is
# forwarded to Rust for that profile.
file(STRINGS "${CMAKE_SOURCE_DIR}/rtconfig.h" FOC_FAST_MATH_BENCH_CONFIG_LINE
    REGEX "^#define FOC_MATH_CPU_FAST_APPROX_BENCHMARK$")
file(STRINGS "${CMAKE_SOURCE_DIR}/rtconfig.h" FOC_FAST_MATH_CANDIDATE_CONFIG_LINE
    REGEX "^#define FOC_MATH_CPU_FAST_APPROX_CANDIDATE$")
if(FLUXRT_BUILD_PROFILE STREQUAL "diagnostic" AND FOC_FAST_MATH_BENCH_CONFIG_LINE)
    list(APPEND FOC_RUST_FEATURE_ARGS --features fast-math-benchmark)
    message(STATUS "FOC CPU fast math: stopped-state benchmark enabled")
    if(FOC_FAST_MATH_CANDIDATE_CONFIG_LINE)
        list(APPEND FOC_RUST_FEATURE_ARGS --features fast-math-candidate)
        message(STATUS "FOC CPU fast math: Diagnostic realtime candidate enabled")
    else()
        message(STATUS "FOC CPU fast math: benchmark only; realtime keeps CORDIC/FPU")
    endif()
elseif(FOC_FAST_MATH_BENCH_CONFIG_LINE OR FOC_FAST_MATH_CANDIDATE_CONFIG_LINE)
    message(STATUS "FOC CPU fast math: ignored outside Diagnostic profile")
endif()

# 24/12 kHz 定时候选只改变 STM32 平台层，Rust 控制频率仍为 12 kHz。这里打印
# 最终档位语义，避免仅凭 .config 把 Production 误认为候选镜像。
file(STRINGS "${CMAKE_SOURCE_DIR}/rtconfig.h" FOC_PWM_MULTIRATE_CONFIG_LINE
    REGEX "^#define FOC_PWM_24K_CONTROL_12K_CANDIDATE$")
if(FLUXRT_BUILD_PROFILE STREQUAL "diagnostic" AND FOC_PWM_MULTIRATE_CONFIG_LINE)
    message(STATUS "FOC timing: Diagnostic 24 kHz PWM / 12 kHz control candidate")
elseif(FOC_PWM_MULTIRATE_CONFIG_LINE)
    message(STATUS "FOC timing: candidate ignored outside Diagnostic; using 12/12 kHz")
else()
    message(STATUS "FOC timing: validated 12/12 kHz default")
endif()

# CONFIGURE_DEPENDS 让新增/删除的 .rs 与 Cargo.toml 自动触发重新配置，否则新文件不会
# 进入 DEPENDS 列表，改动可能被 Ninja 认为"无需重建"。
# CONFIGURE_DEPENDS makes added or removed .rs and Cargo.toml files trigger a
# re-configure; otherwise a new file would never enter DEPENDS and Ninja could consider a
# change up to date.
file(GLOB_RECURSE FOC_RUST_SOURCES CONFIGURE_DEPENDS
    "${FOC_RUST_DIR}/crates/*.rs"
    "${FOC_RUST_DIR}/crates/*/Cargo.toml")

# Rust 静态库作为一个自定义命令的 OUTPUT 参与构建：--locked 固定依赖版本（Flash 与
# WCET 都是被记录的证据），CARGO_PROFILE_RELEASE_OPT_LEVEL 来自本文件的 cache 变量，
# rtconfig.h 也在依赖里，因此改 Kconfig 会连 Rust 一起重编。
# The Rust archive is the OUTPUT of a custom command: --locked pins the dependency
# versions (both Flash size and WCET are recorded evidence), the opt-level comes from the
# cache variable above, and rtconfig.h is a dependency so a Kconfig change rebuilds Rust
# as well.
add_custom_command(
    OUTPUT "${FOC_RUST_ARCHIVE}"
    COMMAND "${CMAKE_COMMAND}" -E env
            "CARGO_TARGET_DIR=${FOC_RUST_TARGET_DIR}"
            "CARGO_PROFILE_RELEASE_OPT_LEVEL=${FLUXRT_RUST_OPT_LEVEL}"
            "${CARGO_EXECUTABLE}" build
            --manifest-path "${FOC_RUST_DIR}/Cargo.toml"
            --package foc-rt-bridge
            --release
            --target "${FOC_RUST_TARGET}"
            --locked
            ${FOC_RUST_FEATURE_ARGS}
    DEPENDS
        ${FOC_RUST_SOURCES}
        "${FOC_RUST_DIR}/Cargo.toml"
        "${FOC_RUST_DIR}/Cargo.lock"
        "${FOC_RUST_DIR}/rust-toolchain.toml"
        "${CMAKE_SOURCE_DIR}/rtconfig.h"
    WORKING_DIRECTORY "${FOC_RUST_DIR}"
    COMMENT "Building Rust FOC static library for ${FOC_RUST_TARGET}"
    VERBATIM
    USES_TERMINAL)

# 让 ELF 依赖 Rust 构建目标，保证第一次构建/清空后 Rust 库先于链接生成。
# Make the ELF depend on the Rust build target so the archive exists before the first
# link after a clean build.
add_custom_target(foc_rust_bridge_build DEPENDS "${FOC_RUST_ARCHIVE}")
add_dependencies(${CMAKE_PROJECT_NAME}.elf foc_rust_bridge_build)
# 覆盖生成器写下的库搜索路径：SCons 生成 CMakeLists.txt 时自定义的 Rust 目录还不存在，
# 生成器只能按固定路径填 LIBPATH。若不覆盖，每个优化等级都会去链接一个过期档位的归档。
# The RT-Thread generator copied the SCons library path before this file was
# included. Replace that generated path so each optimization variant links the
# archive it just built instead of a stale build/rust-target archive.
set_property(TARGET rtt_FOC PROPERTY INTERFACE_LINK_DIRECTORIES
    "${FOC_RUST_TARGET_DIR}/${FOC_RUST_TARGET}/release")
# 生成的工程用 `-lfoc_rt_bridge` 只保证链接顺序，不会让 Ninja 监视归档文件本身；显式
# LINK_DEPENDS 才能保证"只改 Rust 源码"在同一次构建里重链接 ELF。
# The generated project links with `-lfoc_rt_bridge`, which establishes link
# order but does not make Ninja watch the archive path. This explicit dependency
# guarantees that a Rust-only source change relinks the final ELF in the same run.
set_property(TARGET ${CMAKE_PROJECT_NAME}.elf APPEND PROPERTY
    LINK_DEPENDS "${FOC_RUST_ARCHIVE}")

# 实时硬件适配层单独用 -O3：12 kHz 下 ISR 只有约 14167 个内核周期，而全局 C 选项是
# 便于调试的 -Os。链接统计（text/data/bss）与 WCET 必须按本文件的这套选项记录。
# 保留调试符号，便于用 DWT/示波器定位 WCET 超限。
# The ADC ISR has about 14167 core cycles at 12 kHz. Keep debug symbols, but compile
# the realtime hardware adapter with release optimization even when the rest of
# the RT-Thread image uses the developer-friendly project default.
target_compile_options(rtt_FOC PRIVATE -O3)

# 把档位名注入应用层，供启动打印使用。主档位宏三选一，并同时注入应用目标和
# rtt_FOC；能力宏统一由 foc_build_profile.h 派生，避免散落的“非 Production”判断。
# Inject the profile names for the boot report. Exactly one primary profile macro is
# added to both the application and rtt_FOC; foc_build_profile.h derives capabilities
# centrally instead of relying on scattered "not Production" conditions.
target_compile_definitions(${CMAKE_PROJECT_NAME}.elf PRIVATE
    FLUXRT_BUILD_PROFILE_NAME="${FLUXRT_BUILD_PROFILE}"
    FLUXRT_RUST_OPT_LEVEL_NAME="${FLUXRT_RUST_OPT_LEVEL}")

if(FLUXRT_BUILD_PROFILE STREQUAL "diagnostic")
    set(FLUXRT_PRIMARY_PROFILE_DEFINE FLUXRT_DIAGNOSTIC_BUILD=1)
elseif(FLUXRT_BUILD_PROFILE STREQUAL "calibration")
    set(FLUXRT_PRIMARY_PROFILE_DEFINE FLUXRT_CALIBRATION_BUILD=1)
else()
    set(FLUXRT_PRIMARY_PROFILE_DEFINE FLUXRT_PRODUCTION_BUILD=1)
endif()
target_compile_definitions(${CMAKE_PROJECT_NAME}.elf PRIVATE
    ${FLUXRT_PRIMARY_PROFILE_DEFINE})
target_compile_definitions(rtt_FOC PRIVATE
    ${FLUXRT_PRIMARY_PROFILE_DEFINE})

message(STATUS "FluxRT build profile: ${FLUXRT_BUILD_PROFILE}")
message(STATUS "FluxRT Rust opt-level: ${FLUXRT_RUST_OPT_LEVEL}")
