function r=run_lab(id)
startup_course();
names={...
'lab01_rotating_field';...
'lab02_rl_mechanics';...
'lab03_sixstep';...
'lab04_transforms';...
'lab05_pmsm_model';...
'lab06_svpwm';...
'lab07_current_pi';...
'lab08_windup_delay';...
'lab09_current_sensing';...
'lab10_encoder';...
'lab11_foc_closedloop';...
'lab12_sensorless_observer';...
'lab13_mtpa';...
'lab14_field_weakening';...
'lab15_servo_trajectory';...
'lab16_two_inertia';...
'lab17_joint_impedance';...
'lab18_regeneration';...
'lab19_protection_state';...
'lab20_parameter_identification';...
'lab21_multi_axis_timing';...
'lab22_fixedpoint';...
'lab23_other_motors';...
'lab24_loss_thermal'};
assert(isscalar(id) && id==floor(id) && id>=1 && id<=numel(names),'id must be 1..24');
r=feval(names{id});
disp(r.metrics);
fprintf('CSV / MAT / PNG: %s\n',fullfile(mc_root(),'results_matlab',sprintf('L%02d',id)));
end
