function p = foc_refresh_vectors(p)
%FOC_REFRESH_VECTORS Rebuild typed Simulink vectors after named overrides.
p.controllerVector = [ ...
    p.motor.polePairs; p.observer.Rs; p.observer.Ls; p.timing.ts; ...
    p.control.voltageUtilization; p.inverter.dutyMin; p.inverter.dutyMax; ...
    p.limits.softwareTripA; p.bus.minimumV; p.bus.maximumV; ...
    p.control.idKp; p.control.idKi; p.control.currentOutMin; ...
    p.control.currentOutMax; p.startup.alignmentS; p.startup.rampS; ...
    p.startup.transitionS; p.startup.finalSpeedRpm; p.startup.finalCurrentA; ...
    p.startup.closedLoopEnable; p.observer.kSlideV; p.observer.boundaryA; ...
    p.observer.emfAlpha; p.observer.pllKp; p.observer.pllKi; ...
    p.observer.pllOmegaMin; p.observer.pllOmegaMax; ...
    p.observer.reliabilityDecimator; p.observer.reliabilityMinMeanRpm; ...
    p.observer.reliabilityMinEmfV; p.observer.reliabilityMaxVarRatio; ...
    p.observer.reliabilityWindows; p.startup.observerAcquisitionTimeoutS; ...
    p.startup.observerLossTimeoutS; p.timing.speedLoopDivider; ...
    p.control.speedKp; p.control.speedKi; p.control.speedOutMin; ...
    p.control.speedOutMax; p.startup.closedLoopSpeedRampRpmPerS; ...
    p.startup.speedPiPreloadRatio; p.startup.closedLoopCurrentSlewAPerS; ...
    p.motor.maxSpeedRpm; p.inverter.deadTimeNs; ...
    double(p.inverter.deadTimeCompensationEnabled); ...
    p.inverter.deadTimeCompensationGain; ...
    p.inverter.deadTimeCompensationCurrentBandA; ...
    double(p.inverter.observerDeadTimeCompensationEnabled)];
p.plantVector = [ ...
    p.motor.Rs; p.motor.Ld; p.motor.Lq; p.motor.fluxLinkageWb; ...
    p.motor.polePairs; p.motor.inertiaKgM2; p.motor.frictionNmS; ...
    p.timing.ts; double(p.inverter.enableDeadTime); p.inverter.deadTimeNs];
end
