function out = load_fluxrt_simulation_contract(projectRoot,bundleRelative)
%LOAD_FLUXRT_SIMULATION_CONTRACT Strict P1.3 shared-contract loader.
% Reads the exact same schema/profile/scenario/trace/comparison files as
% rust/crates/foc-sim. Unknown versions, fields, units, hashes and identities
% fail closed. This function performs no serial, target or power-stage I/O.

if nargin < 1 || isempty(projectRoot)
    projectRoot = fileparts(fileparts(mfilename('fullpath')));
end
if nargin < 2 || isempty(bundleRelative)
    bundleRelative = 'simulation/contracts/legacy_speed_start.bundle.json';
end
projectRoot = char(projectRoot);
bundlePath = safe_path(projectRoot,char(bundleRelative));
[bundle,bundleBytes] = read_json(bundlePath);
exact_fields(bundle,{ ...
    'contract','version','bundle_id','units','schema_path','schema_sha256', ...
    'schema_id','schema_version','profile_path','profile_sha256','profile_id', ...
    'profile_revision','board_id','motor_id','inverter_id','runtime_config_crc32', ...
    'product_contract_version','bridge_abi_version','source_revision','model_revision', ...
    'scenario_path','scenario_sha256','scenario_id', ...
    'scenario_revision','trace_schema_path','trace_schema_sha256','trace_schema_id', ...
    'trace_schema_version','comparison_path','comparison_sha256','comparison_id', ...
    'comparison_version'},'bundle');
contract_header(bundle,'fluxrt-simulation-bundle','bundle');

[schema,schemaBytes] = read_reference(projectRoot,bundle,'schema_path','schema_sha256');
exact_fields(schema,{'contract','version','schema_id','units','bundle_required', ...
    'profile_required','scenario_required','trace_required','comparison_required'},'schema');
contract_header(schema,'fluxrt-simulation-schema','schema');
same_identity(bundle,'schema_id','schema_version',schema,'schema_id','version','schema');

[profile,profileBytes] = read_reference(projectRoot,bundle,'profile_path','profile_sha256');
exact_fields(profile,{ ...
    'contract','version','profile_id','revision','units','board_id','motor_id', ...
    'inverter_id','runtime_config_crc32','product_contract_version','bridge_abi_version', ...
    'source_revision','model_revision','pole_pairs','stator_resistance_ohm','ld_h','lq_h', ...
    'flux_linkage_wb','rated_current_a','max_mechanical_velocity_rad_s', ...
    'nominal_bus_voltage_v','inertia_kg_m2','viscous_friction_nm_s', ...
    'pwm_frequency_hz','control_frequency_hz','speed_loop_frequency_hz', ...
    'actuation_delay_pwm_ticks'},'profile');
contract_header(profile,'fluxrt-simulation-profile','profile');
same_identity(bundle,'profile_id','profile_revision',profile,'profile_id','revision','profile');
profileIdentityFields = {'board_id','motor_id','inverter_id','runtime_config_crc32', ...
    'product_contract_version','bridge_abi_version','source_revision','model_revision'};
for k = 1:numel(profileIdentityFields)
    field = profileIdentityFields{k};
    assert(strcmp(char(bundle.(field)),char(profile.(field))), ...
        'FluxRT:Contract:Identity','profile %s mismatch',field);
end
validate_profile(profile);

[scenario,scenarioBytes] = read_reference(projectRoot,bundle,'scenario_path','scenario_sha256');
exact_fields(scenario,{ ...
    'contract','version','scenario_id','revision','seed','units','profile_id', ...
    'profile_revision','duration_s','trace_decimation','initial_velocity_rad_s', ...
    'initial_electrical_angle_rad','initial_temperature_k','dc_bus_voltage_v', ...
    'command_at_s','axis_request','control_mode','input_mode','feedback_mode', ...
    'target_velocity_rad_s','startup_duration_s','load_step_at_s','load_torque_nm','sensor_noise_std_a', ...
    'sensor_offset_a','sensor_quantization_a','sensor_delay_control_ticks','sensor_fault', ...
    'power_source_model','brake_resistor_model','d1_events'},'scenario');
contract_header(scenario,'fluxrt-simulation-scenario','scenario');
same_identity(bundle,'scenario_id','scenario_revision',scenario,'scenario_id','revision','scenario');
d1ActualEvents = validate_scenario(scenario,profile);

[traceSchema,traceBytes] = read_reference(projectRoot,bundle, ...
    'trace_schema_path','trace_schema_sha256');
exact_fields(traceSchema,{'contract','version','trace_schema_id','units','channels'}, ...
    'trace schema');
contract_header(traceSchema,'fluxrt-trace-schema','trace schema');
same_identity(bundle,'trace_schema_id','trace_schema_version',traceSchema, ...
    'trace_schema_id','version','trace schema');
traceNames = validate_trace_schema(traceSchema);

[comparison,comparisonBytes] = read_reference(projectRoot,bundle, ...
    'comparison_path','comparison_sha256');
exact_fields(comparison,{'contract','version','comparison_id','units','d0_exact', ...
    'd1_exact','d1_event_tick_tolerance','numeric_tolerances', ...
    'motion_numeric_tolerances'},'comparison');
contract_header(comparison,'fluxrt-comparison-gates','comparison');
same_identity(bundle,'comparison_id','comparison_version',comparison, ...
    'comparison_id','version','comparison');
validate_comparison(comparison,traceNames);

out = struct();
out.bundle = bundle;
out.schema = schema;
out.profile = profile;
out.scenario = scenario;
out.traceSchema = traceSchema;
out.comparison = comparison;
out.engineId = 'fluxrt.matlab.lifecycle.v1';
out.d1ActualEvents = d1ActualEvents;
out.identity = struct( ...
    'bundleSha256',sha256_hex(bundleBytes), ...
    'schemaSha256',sha256_hex(schemaBytes), ...
    'profileSha256',sha256_hex(profileBytes), ...
    'scenarioSha256',sha256_hex(scenarioBytes), ...
    'traceSchemaSha256',sha256_hex(traceBytes), ...
    'comparisonSha256',sha256_hex(comparisonBytes));
% Adapter only: canonical storage remains rad/s. RPM is derived here solely
% because the pre-P1.3 run_foc_sim entry still accepts an engineering-unit RPM.
out.legacyReference = struct( ...
    'durationS',double(scenario.duration_s), ...
    'targetSpeedRpm',double(scenario.target_velocity_rad_s)*30/pi, ...
    'loadStepAtS',double(scenario.load_step_at_s), ...
    'loadTorqueNm',double(scenario.load_torque_nm), ...
    'traceDecimation',double(scenario.trace_decimation), ...
    'pwmFrequencyHz',double(profile.pwm_frequency_hz), ...
    'controlFrequencyHz',double(profile.control_frequency_hz), ...
    'actuationDelayPwmTicks',double(profile.actuation_delay_pwm_ticks));
end

function validate_profile(p)
assert(~isempty(regexp(char(p.runtime_config_crc32),'^0x[0-9a-f]{8}$','once')) && ...
    strcmp(char(p.product_contract_version),'0x00010000') && ...
    strcmp(char(p.bridge_abi_version),'0x00150000') && ...
    ~isempty(char(p.source_revision)) && ~isempty(char(p.model_revision)), ...
    'FluxRT:Contract:Identity','profile ABI/config/source identity is invalid');
positive = {'pole_pairs','stator_resistance_ohm','ld_h','lq_h','flux_linkage_wb', ...
    'rated_current_a','max_mechanical_velocity_rad_s','nominal_bus_voltage_v', ...
    'inertia_kg_m2','pwm_frequency_hz','control_frequency_hz','speed_loop_frequency_hz'};
for k = 1:numel(positive)
    value = finite_scalar(p.(positive{k}),['profile.' positive{k}]);
    assert(value > 0,'FluxRT:Contract:Range','%s must be positive',positive{k});
end
assert(finite_scalar(p.viscous_friction_nm_s,'profile.viscous_friction_nm_s') >= 0, ...
    'FluxRT:Contract:Range','viscous_friction_nm_s must be non-negative');
integers = {'revision','pole_pairs','pwm_frequency_hz','control_frequency_hz', ...
    'speed_loop_frequency_hz','actuation_delay_pwm_ticks'};
for k = 1:numel(integers), unsigned_integer(p.(integers{k}),['profile.' integers{k}]); end
assert(mod(p.pwm_frequency_hz,p.control_frequency_hz)==0, ...
    'FluxRT:Contract:Timing','PWM/control ratio must be integral');
assert(mod(p.control_frequency_hz,p.speed_loop_frequency_hz)==0, ...
    'FluxRT:Contract:Timing','control/speed ratio must be integral');
assert(p.actuation_delay_pwm_ticks <= p.pwm_frequency_hz/p.control_frequency_hz, ...
    'FluxRT:Contract:Timing','actuation delay exceeds one control period');
end

function actual = validate_scenario(s,p)
assert(strcmp(char(s.profile_id),char(p.profile_id)) && s.profile_revision==p.revision, ...
    'FluxRT:Contract:Identity','scenario profile identity mismatch');
assert(strcmp(char(s.axis_request),'ClosedLoopControl') && ...
    strcmp(char(s.control_mode),'Velocity') && strcmp(char(s.input_mode),'Passthrough') && ...
    strcmp(char(s.feedback_mode),'Sensorless'), ...
    'FluxRT:Contract:Mode','legacy_speed_start mode tuple is not canonical');
assert(abs(double(s.target_velocity_rad_s)-524*pi/30)<=1e-6, ...
    'FluxRT:Contract:Target','legacy_speed_start is not the frozen 524 rpm intent');
assert(finite_scalar(s.duration_s,'scenario.duration_s')>0 && ...
    finite_scalar(s.startup_duration_s,'scenario.startup_duration_s')>0 && ...
    finite_scalar(s.initial_temperature_k,'scenario.initial_temperature_k')>0 && ...
    finite_scalar(s.dc_bus_voltage_v,'scenario.dc_bus_voltage_v')>0, ...
    'FluxRT:Contract:Range','invalid scenario duration/temperature/bus');
unsigned_integer(s.revision,'scenario.revision');
unsigned_integer(s.seed,'scenario.seed');
unsigned_integer(s.trace_decimation,'scenario.trace_decimation');
assert(s.trace_decimation>0,'FluxRT:Contract:Range','trace_decimation must be non-zero');
assert(s.command_at_s>=0 && s.command_at_s<=s.duration_s && ...
    s.load_step_at_s>=0 && s.load_step_at_s<=s.duration_s, ...
    'FluxRT:Contract:Range','scenario event time is outside duration');

events = s.d1_events;
assert(isstruct(events) && ~isempty(events),'FluxRT:Contract:D1','d1_events must be non-empty');
lastTick = -1; lastRank = 0;
for k = 1:numel(events)
    exact_fields(events(k),{'control_tick','axis_state','controller_internal_state', ...
        'active_source','event','output_enabled','fault_flags'},'D1 event');
    tick = unsigned_integer(events(k).control_tick,'D1 control_tick');
    faults = unsigned_integer(events(k).fault_flags,'D1 fault_flags');
    rank = axis_state_rank(char(events(k).axis_state));
    assert(tick>lastTick && rank>=lastRank,'FluxRT:Contract:D1', ...
        'D1 ticks/order must be strictly forward');
    enabled = logical_scalar(events(k).output_enabled,'D1 output_enabled');
    if any(strcmp(char(events(k).axis_state), ...
            {'Uninitialized','Disabled','Calibration','Stopping','FaultLatched'}))
        assert(~enabled,'FluxRT:Contract:D1','non-running state cannot enable output');
    end
    if strcmp(char(events(k).axis_state),'FaultLatched')
        assert(faults~=0,'FluxRT:Contract:D1','FaultLatched requires a fault bit');
    end
    lastTick = tick; lastRank = rank;
end
assert(events(1).control_tick==0 && strcmp(char(events(1).axis_state),'Disabled') && ...
    ~logical(events(1).output_enabled) && events(1).fault_flags==0, ...
    'FluxRT:Contract:D1','D1 must start disabled and fault-free');
states = arrayfun(@(x)string(x.axis_state),events);
assert(any(states=="Startup") && any(states=="ClosedLoop"), ...
    'FluxRT:Contract:D1','D1 must include Startup and ClosedLoop');
assert(events(end).control_tick <= round(s.duration_s*p.control_frequency_hz), ...
    'FluxRT:Contract:D1','D1 event exceeds scenario duration');
actual = run_d1_lifecycle_engine(s,p);
assert(numel(actual)==numel(events),'FluxRT:Contract:D1', ...
    'D1 lifecycle engine event count differs from scenario oracle');
for k = 1:numel(events)
    assert(actual(k).control_tick==events(k).control_tick && ...
        strcmp(actual(k).axis_state,char(events(k).axis_state)) && ...
        strcmp(actual(k).controller_internal_state,char(events(k).controller_internal_state)) && ...
        strcmp(actual(k).active_source,char(events(k).active_source)) && ...
        strcmp(actual(k).event,char(events(k).event)) && ...
        actual(k).output_enabled==logical(events(k).output_enabled) && ...
        actual(k).fault_flags==events(k).fault_flags, ...
        'FluxRT:Contract:D1','D1 lifecycle engine differs from scenario oracle');
end
end

function events = run_d1_lifecycle_engine(s,p)
% Independent MATLAB implementation. The expected d1_events array is not read.
commandTick = round(double(s.command_at_s)*double(p.control_frequency_hz));
closedLoopTick = commandTick + ...
    round(double(s.startup_duration_s)*double(p.control_frequency_hz));
events = repmat(struct('control_tick',0,'axis_state','','controller_internal_state','', ...
    'active_source','','event','','output_enabled',false,'fault_flags',0),1,3);
events(1) = struct('control_tick',0,'axis_state','Disabled', ...
    'controller_internal_state','Disabled','active_source','none','event','axis_ready', ...
    'output_enabled',false,'fault_flags',0);
events(2) = struct('control_tick',commandTick+1,'axis_state','Startup', ...
    'controller_internal_state','Alignment','active_source','product_command', ...
    'event','start_requested', ...
    'output_enabled',true,'fault_flags',0);
events(3) = struct('control_tick',closedLoopTick,'axis_state','ClosedLoop', ...
    'controller_internal_state','ClosedLoop','active_source','product_command', ...
    'event','observer_handover_complete', ...
    'output_enabled',true,'fault_flags',0);
end

function names = validate_trace_schema(t)
channels = t.channels;
assert(isstruct(channels) && ~isempty(channels),'FluxRT:Contract:Trace','channels missing');
allowedKinds = ["identity","time","state","reference","current","voltage","modulation", ...
    "angle","velocity","observer","mechanical","thermal","energy","safety"];
names = strings(1,numel(channels));
for k = 1:numel(channels)
    exact_fields(channels(k),{'name','unit','kind'},'trace channel');
    names(k) = string(channels(k).name);
    assert(strlength(names(k))>0 && strlength(string(channels(k).unit))>0 && ...
        any(string(channels(k).kind)==allowedKinds), ...
        'FluxRT:Contract:Trace','invalid trace channel');
end
assert(numel(unique(names))==numel(names),'FluxRT:Contract:Trace','duplicate trace channel');
required = ["scenario_identity","profile_identity","config_identity","model_revision", ...
    "time_s","control_tick","pwm_tick","sample_age_s","axis_state", ...
    "controller_internal_state","control_mode","input_mode","active_source","event", ...
    "velocity_reference_rad_s", ...
    "id_reference_a","iq_reference_a","phase_current_u_a","phase_current_v_a", ...
    "phase_current_w_a","id_a","iq_a","vd_command_v","vq_command_v", ...
    "dc_bus_voltage_v","duty_u","duty_v","duty_w","true_electrical_angle_rad", ...
    "forced_electrical_angle_rad","estimated_electrical_angle_rad", ...
    "selected_electrical_angle_rad","true_velocity_rad_s","estimated_velocity_rad_s", ...
    "selected_velocity_rad_s","observer_quality","observer_reliable", ...
    "electromagnetic_torque_nm","load_torque_nm","mechanical_position_rad", ...
    "motor_temperature_k","bus_power_w","regen_power_w","fault_flags", ...
    "derating_ratio","command_timeout","output_enabled"];
assert(all(ismember(required,names)),'FluxRT:Contract:Trace','required trace channel missing');
end

function validate_comparison(c,traceNames)
d0 = ["bundle_id","bundle_sha256","schema_id","schema_version","schema_sha256", ...
    "profile_id","profile_revision","profile_sha256", ...
    "board_id","motor_id","inverter_id","runtime_config_crc32", ...
    "product_contract_version","bridge_abi_version","source_revision","model_revision", ...
    "workspace_revision", ...
    "scenario_id","scenario_revision","scenario_sha256","trace_schema_id", ...
    "trace_schema_version","trace_schema_sha256","comparison_id","comparison_version", ...
    "comparison_sha256"];
d1 = ["control_tick","axis_state","controller_internal_state","active_source","event", ...
    "output_enabled","fault_flags","event_order"];
assert(isequal(sort(to_strings(c.d0_exact)),sort(d0)) && ...
    isequal(sort(to_strings(c.d1_exact)),sort(d1)), ...
    'FluxRT:Contract:Comparison','D0/D1 exact sets differ from V1');
assert(unsigned_integer(c.d1_event_tick_tolerance,'d1_event_tick_tolerance')==0, ...
    'FluxRT:Contract:Comparison','D1 V1 tick tolerance must be zero');
t = c.numeric_tolerances;
assert(isstruct(t),'FluxRT:Contract:Comparison','numeric_tolerances must be objects');
seen = strings(1,numel(t));
for k = 1:numel(t)
    exact_fields(t(k),{'channel','absolute','relative'},'numeric tolerance');
    seen(k) = string(t(k).channel);
    assert(any(seen(k)==traceNames) && finite_scalar(t(k).absolute,'absolute')>=0 && ...
        finite_scalar(t(k).relative,'relative')>=0, ...
        'FluxRT:Contract:Comparison','invalid numeric tolerance');
end
assert(numel(unique(seen))==numel(seen),'FluxRT:Contract:Comparison', ...
    'duplicate numeric tolerance');

motionNames = ["time_s","command_position_rad","command_velocity_rad_s", ...
    "command_torque_nm","feedback_position_rad","feedback_velocity_rad_s", ...
    "feedback_iq_a","planned_position_rad","planned_velocity_rad_s", ...
    "planned_torque_nm","output_velocity_ref_rad_s","output_torque_nm", ...
    "output_id_a","output_iq_a","velocity_integrator_nm"];
mt = c.motion_numeric_tolerances;
assert(isstruct(mt),'FluxRT:Contract:Comparison', ...
    'motion_numeric_tolerances must be objects');
motionSeen = strings(1,numel(mt));
for k = 1:numel(mt)
    exact_fields(mt(k),{'channel','absolute','relative'},'motion numeric tolerance');
    motionSeen(k) = string(mt(k).channel);
    assert(strlength(motionSeen(k))>0 && ...
        finite_scalar(mt(k).absolute,'absolute')>=0 && ...
        finite_scalar(mt(k).relative,'relative')>=0, ...
        'FluxRT:Contract:Comparison','invalid motion numeric tolerance');
end
assert(numel(unique(motionSeen))==numel(motionSeen), ...
    'FluxRT:Contract:Comparison','duplicate motion numeric tolerance');
assert(isequal(sort(motionSeen),sort(motionNames)), ...
    'FluxRT:Contract:Comparison', ...
    'motion numeric tolerance channels differ from V1');
end

function [document,bytes] = read_reference(root,bundle,pathField,hashField)
path = safe_path(root,char(bundle.(pathField)));
[document,bytes] = read_json(path);
actual = sha256_hex(bytes); expected = char(bundle.(hashField));
assert(~isempty(regexp(expected,'^[0-9a-f]{64}$','once')) && strcmp(actual,expected), ...
    'FluxRT:Contract:Hash','%s mismatch: expected %s, got %s',hashField,expected,actual);
end

function [value,bytes] = read_json(path)
fid = fopen(path,'rb');
assert(fid>=0,'FluxRT:Contract:IO','cannot open %s',path);
cleanup = onCleanup(@()fclose(fid));
bytes = fread(fid,Inf,'*uint8');
clear cleanup
try
    value = jsondecode(native2unicode(bytes','UTF-8'));
catch problem
    error('FluxRT:Contract:JSON','cannot parse %s: %s',path,problem.message);
end
assert(isstruct(value) && isscalar(value),'FluxRT:Contract:JSON','root must be an object');
end

function path = safe_path(root,relative)
assert(~isempty(relative) && relative(1)~='/' && isempty(strfind(relative,'\')) && ...
    isempty(strfind(relative,':')),'FluxRT:Contract:Path','unsafe path %s',relative);
parts = regexp(relative,'/','split');
assert(all(~cellfun('isempty',parts)) && ~any(strcmp(parts,'.')) && ~any(strcmp(parts,'..')), ...
    'FluxRT:Contract:Path','unsafe path %s',relative);
path = fullfile(root,parts{:});
end

function contract_header(value,expected,label)
assert(strcmp(char(value.contract),expected) && ...
    unsigned_integer(value.version,[label '.version'])==1, ...
    'FluxRT:Contract:Version','unknown contract/version for %s',label);
assert(strcmp(char(value.units),'SI'),'FluxRT:Contract:Units','%s.units must be SI',label);
end

function same_identity(a,aId,aVersion,b,bId,bVersion,label)
assert(strcmp(char(a.(aId)),char(b.(bId))) && a.(aVersion)==b.(bVersion), ...
    'FluxRT:Contract:Identity','%s identity mismatch',label);
end

function exact_fields(value,expected,label)
actual = sort(string(fieldnames(value))); expected = sort(string(expected(:)));
assert(isequal(actual,expected),'FluxRT:Contract:Fields','%s field set mismatch',label);
end

function value = finite_scalar(value,label)
assert(isnumeric(value) && isreal(value),'FluxRT:Contract:Number', ...
    '%s must be numeric',label);
value = double(value);
assert(isscalar(value) && isfinite(value), ...
    'FluxRT:Contract:Number','%s must be finite scalar',label);
end

function value = unsigned_integer(value,label)
value = finite_scalar(value,label);
assert(value>=0 && value==fix(value),'FluxRT:Contract:Number', ...
    '%s must be an unsigned integer',label);
end

function value = logical_scalar(value,label)
assert(islogical(value) && isscalar(value),'FluxRT:Contract:Boolean', ...
    '%s must be logical scalar',label);
end

function rank = axis_state_rank(state)
states = {'Uninitialized','Disabled','Calibration','Startup','ClosedLoop','Stopping','FaultLatched'};
rank = find(strcmp(state,states),1)-1;
assert(~isempty(rank),'FluxRT:Contract:D1','unknown AxisState %s',state);
end

function values = to_strings(value)
if iscell(value), values = string(value); else, values = string(value(:))'; end
values = reshape(values,1,[]);
assert(numel(unique(values))==numel(values),'FluxRT:Contract:Comparison','duplicate exact field');
end

function hash = sha256_hex(bytes)
digest = javaMethod('getInstance','java.security.MessageDigest','SHA-256');
digest.update(typecast(uint8(bytes),'int8'));
raw = typecast(digest.digest(),'uint8');
hash = lower(reshape(dec2hex(raw,2).',1,[]));
end
