function out = run_foc_validation(varargin)
%RUN_FOC_VALIDATION Exercise current firmware-equivalent open/closed paths.
ip = inputParser;
ip.addParameter('openDuration',5,@(x)isnumeric(x)&&isscalar(x)&&x>0);
ip.addParameter('closedDuration',10,@(x)isnumeric(x)&&isscalar(x)&&x>0);
ip.addParameter('rebuild',false,@(x)islogical(x)||isnumeric(x));
ip.parse(varargin{:});
o = ip.Results;

fprintf('=== current firmware parameter check ===\n');
p = init_foc_params();
checks = [ ...
    abs(p.control.idKp-7.197815315)<1e-6; ...
    abs(p.control.idKi-35989.076576)<1e-3; ...
    abs(p.observer.kSlideV-4.0)<1e-9; ...
    abs(p.observer.boundaryA-0.16)<1e-9; ...
    abs(p.observer.pllKp-80)<1e-9; ...
    abs(p.observer.pllKi-1000)<1e-9; ...
    p.observer.reliabilityWindows==2; ...
    abs(p.observer.reliabilityMaxVarRatio-0.01)<1e-12; ...
    numel(p.controllerVector)==48; ...
    ~p.inverter.deadTimeCompensationEnabled; ...
    ~p.inverter.observerDeadTimeCompensationEnabled; ...
    abs(p.inverter.deadTimeCompensationCurrentBandA-0.005)<1e-12];
assert(all(checks),'MATLAB parameters drifted from the current Rust defaults.');
fprintf('parameters: PASS\n');

fprintf('\n=== open-loop telemetry run ===\n');
openRun = run_foc_sim('closedLoop',false,'duration',o.openDuration, ...
    'enableDeadTime',false,'rebuild',o.rebuild);
fprintf('final true/observer : %.3f / %.3f rpm\n', ...
    openRun.trueSpeedRpm(end),openRun.obsSpeedRpm(end));
fprintf('final state/faults  : %.0f / 0x%X\n', ...
    openRun.state(end),uint32(max(openRun.faultFlags)));
fprintf('reliable samples    : %d / %d\n', ...
    sum(openRun.reliable~=0),numel(openRun.reliable));
assert(openRun.state(end)==5 && max(openRun.faultFlags)==0, ...
    'Open-loop regression did not end safely in OpenLoopHold.');

fprintf('\n=== observer handoff and closed-loop run ===\n');
if bdIsLoaded('foc_bringup'), close_system('foc_bringup',0); end
closedRun = run_foc_sim('closedLoop',true,'duration',o.closedDuration, ...
    'enableDeadTime',false,'rebuild',false);
i6 = find(closedRun.state==6,1);
i7 = find(closedRun.state==7,1);
assert(~isempty(i6)&&~isempty(i7),'Closed-loop run never reached transition/state 7.');
assert(closedRun.state(end)==7 && max(closedRun.faultFlags)==0, ...
    'Closed-loop run ended outside state 7 or latched a fault.');
fprintf('transition/closed   : %.6f / %.6f s\n', ...
    closedRun.time(i6),closedRun.time(i7));
fprintf('final true/observer : %.3f / %.3f rpm\n', ...
    closedRun.trueSpeedRpm(end),closedRun.obsSpeedRpm(end));
fprintf('final Iq reference  : %.6f A\n',closedRun.iqRef(end));
fprintf('max raw Iq step     : %.6f A\n',max(abs(diff(closedRun.iqRef))));

out = struct('parameters',p,'open',openRun,'closed',closedRun);
fprintf('\nVALIDATION PASS (model/host level only; not new hardware proof).\n');
if bdIsLoaded('foc_bringup'), close_system('foc_bringup',0); end
end
