function result = validate_fluxrt_simulation_contract(projectRoot,outputPath)
%VALIDATE_FLUXRT_SIMULATION_CONTRACT Emit deterministic D0/D1 evidence.
% The result format intentionally matches `foc-contract-check`; a comparison
% script can therefore reject any Rust/MATLAB identity or event disagreement.

if nargin < 1 || isempty(projectRoot)
    projectRoot = fileparts(fileparts(mfilename('fullpath')));
end
if nargin < 2, outputPath = ''; end
loaded = load_fluxrt_simulation_contract(projectRoot);
b = loaded.bundle; s = loaded.scenario; id = loaded.identity;
workspaceRevision = getenv('FLUXRT_WORKSPACE_REVISION');
if isempty(workspaceRevision), workspaceRevision = 'UNRECORDED'; end
lines = { ...
    'contract_gate_result_version=1'; ...
    ['engine_id=' loaded.engineId]; ...
    ['bundle_id=' char(b.bundle_id)]; ...
    ['bundle_sha256=' id.bundleSha256]; ...
    ['schema_id=' char(b.schema_id)]; ...
    sprintf('schema_version=%.0f',b.schema_version); ...
    ['schema_sha256=' id.schemaSha256]; ...
    ['profile_id=' char(b.profile_id)]; ...
    sprintf('profile_revision=%.0f',b.profile_revision); ...
    ['profile_sha256=' id.profileSha256]; ...
    ['board_id=' char(b.board_id)]; ...
    ['motor_id=' char(b.motor_id)]; ...
    ['inverter_id=' char(b.inverter_id)]; ...
    ['runtime_config_crc32=' char(b.runtime_config_crc32)]; ...
    ['product_contract_version=' char(b.product_contract_version)]; ...
    ['bridge_abi_version=' char(b.bridge_abi_version)]; ...
    ['source_revision=' char(b.source_revision)]; ...
    ['model_revision=' char(b.model_revision)]; ...
    ['workspace_revision=' workspaceRevision]; ...
    ['scenario_id=' char(b.scenario_id)]; ...
    sprintf('scenario_revision=%.0f',b.scenario_revision); ...
    ['scenario_sha256=' id.scenarioSha256]; ...
    ['trace_schema_id=' char(b.trace_schema_id)]; ...
    sprintf('trace_schema_version=%.0f',b.trace_schema_version); ...
    ['trace_schema_sha256=' id.traceSchemaSha256]; ...
    ['comparison_id=' char(b.comparison_id)]; ...
    sprintf('comparison_version=%.0f',b.comparison_version); ...
    ['comparison_sha256=' id.comparisonSha256]; ...
    'd0=PASS'; ...
    sprintf('d1_event_tick_tolerance=%.0f',loaded.comparison.d1_event_tick_tolerance); ...
    sprintf('d1_event_count=%d',numel(loaded.d1ActualEvents))};
for k = 1:numel(loaded.d1ActualEvents)
    event = loaded.d1ActualEvents(k);
    lines{end+1,1} = sprintf('d1_event_%d=%.0f,%s,%s,%s,%s,%d,%.0f',k-1, ...
        event.control_tick,char(event.axis_state),char(event.controller_internal_state), ...
        char(event.active_source),char(event.event),logical(event.output_enabled), ...
        event.fault_flags); %#ok<AGROW>
end
lines{end+1,1} = 'd1=PASS';
text = [strjoin(lines,newline) newline];
if ~isempty(outputPath)
    fid = fopen(char(outputPath),'wb');
    assert(fid>=0,'FluxRT:Contract:IO','cannot create %s',char(outputPath));
    cleanup = onCleanup(@()fclose(fid));
    fwrite(fid,unicode2native(text,'UTF-8'),'uint8');
    clear cleanup
end
result = struct('lines',{lines},'text',text,'loaded',loaded);
fprintf('FLUXRT_SIM_CONTRACT_PASS bundle=%s events=%d target_rad_s=%.6f target_rpm=%.3f\n', ...
    char(b.bundle_id),numel(s.d1_events),s.target_velocity_rad_s, ...
    loaded.legacyReference.targetSpeedRpm);
end
