function report = validate_multirate_timing(varargin)
%VALIDATE_MULTIRATE_TIMING Compare 12/12 kHz and 24/12 kHz timing models.
%
% This is a PC/Simulink design gate only. It never opens a serial port or enables
% the power stage. Both cases keep the controller at 12 kHz; only the carrier/plant
% step and the integer PWM-boundary actuation delay change.

ip = inputParser;
ip.addParameter('duration',7,@(x)isnumeric(x)&&isscalar(x)&&x>=5);
ip.addParameter('outputDir',fullfile(fileparts(mfilename('fullpath')),'results'), ...
    @(s)ischar(s)||isstring(s));
ip.parse(varargin{:});
o = ip.Results;

common = {'closedLoop',true,'duration',o.duration,'enableDeadTime',true, ...
    'enableDeadTimeCompensation',true, ...
    'enableObserverDeadTimeCompensation',true};

baseline = run_foc_sim(common{:},'pwmFrequencyHz',12000, ...
    'controlFrequencyHz',12000,'actuationDelayPwmTicks',1,'rebuild',true);
if bdIsLoaded('foc_bringup'), close_system('foc_bringup',0); end
candidate = run_foc_sim(common{:},'pwmFrequencyHz',24000, ...
    'controlFrequencyHz',12000,'actuationDelayPwmTicks',2,'rebuild',false);
if bdIsLoaded('foc_bringup'), close_system('foc_bringup',0); end

report = struct();
report.boundary = ['PC/Simulink model only; no hardware timing, acoustic or ' ...
    'current-ripple proof.'];
report.baseline = metrics(baseline,o.duration);
report.candidate = metrics(candidate,o.duration);
report.delta = struct( ...
    'steadySpeedStdRpm',report.candidate.steadySpeedStdRpm- ...
        report.baseline.steadySpeedStdRpm, ...
    'observerRmseRpm',report.candidate.observerRmseRpm- ...
        report.baseline.observerRmseRpm, ...
    'iqTrackingRmseA',report.candidate.iqTrackingRmseA- ...
        report.baseline.iqTrackingRmseA, ...
    'idRmseA',report.candidate.idRmseA-report.baseline.idRmseA);

assert(report.baseline.finalState==7 && report.candidate.finalState==7, ...
    'Both timing cases must finish in ClosedLoop/state 7.');
assert(report.baseline.maxFaultFlags==0 && report.candidate.maxFaultFlags==0, ...
    'A timing case latched a fault.');
assert(report.baseline.controlSamples==round(o.duration*12000) && ...
       report.candidate.controlSamples==round(o.duration*12000), ...
    'Control sample count drifted from 12 kHz.');
assert(candidate.p.timing.pwmTicksPerControl==2 && ...
       candidate.p.timing.actuationDelayPwmTicks==2 && ...
       baseline.p.timing.actuationDelayPwmTicks==1, ...
    'Cases did not run the target-derived one-control-tick preload delay.');

outputDir = char(o.outputDir);
if ~exist(outputDir,'dir'), mkdir(outputDir); end
jsonPath = fullfile(outputDir,'multirate_12k_vs_24k.json');
fid = fopen(jsonPath,'w');
if fid < 0, error('validate_multirate_timing:write','Cannot write %s.',jsonPath); end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid,'%s',jsonencode(report,'PrettyPrint',true));
clear cleanup

fprintf(['FOC_MULTIRATE_MATLAB_PASS baseline_state=%d candidate_state=%d ' ...
    'baseline_std_rpm=%.6f candidate_std_rpm=%.6f ' ...
    'baseline_obs_rmse_rpm=%.6f candidate_obs_rmse_rpm=%.6f ' ...
    'baseline_iq_rmse_a=%.9f candidate_iq_rmse_a=%.9f samples=%d\n'], ...
    report.baseline.finalState,report.candidate.finalState, ...
    report.baseline.steadySpeedStdRpm,report.candidate.steadySpeedStdRpm, ...
    report.baseline.observerRmseRpm,report.candidate.observerRmseRpm, ...
    report.baseline.iqTrackingRmseA,report.candidate.iqTrackingRmseA, ...
    report.candidate.controlSamples);
fprintf('FOC_MULTIRATE_MATLAB_REPORT=%s\n',jsonPath);
end

function m = metrics(r,duration)
steady = r.time >= max(duration-2,2.5);
speed = r.trueSpeedRpm(steady);
observerError = r.obsSpeedRpm(steady)-speed;
iqError = r.iqMeas(steady)-r.iqRef(steady);
idError = r.idMeas(steady);
i6 = find(r.state==6,1);
i7 = find(r.state==7,1);
m = struct( ...
    'pwmFrequencyHz',r.p.timing.pwmFrequencyHz, ...
    'controlFrequencyHz',r.p.timing.controlFrequencyHz, ...
    'actuationDelayPwmTicks',r.p.timing.actuationDelayPwmTicks, ...
    'controlSamples',numel(r.time), ...
    'finalState',r.state(end), ...
    'maxFaultFlags',max(r.faultFlags), ...
    'transitionTimeS',time_or_nan(r.time,i6), ...
    'closedLoopTimeS',time_or_nan(r.time,i7), ...
    'finalTrueSpeedRpm',r.trueSpeedRpm(end), ...
    'steadySpeedMeanRpm',mean(speed), ...
    'steadySpeedStdRpm',std(speed), ...
    'observerRmseRpm',sqrt(mean(observerError.^2)), ...
    'iqTrackingRmseA',sqrt(mean(iqError.^2)), ...
    'idRmseA',sqrt(mean(idError.^2)), ...
    'peakPhaseCurrentA',max(abs(r.phaseCurrents),[],'all'));
end

function value = time_or_nan(time,index)
if isempty(index), value = NaN; else, value = time(index); end
end
