[package]
name = "foc-control"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "foc_control"
crate-type = ["rlib"]

[features]
default = []
motion-control = []
advanced-foc = []
sensorless-foc = []

[dependencies]
foc-algorithm = { path = "../foc-algorithm" }
libm = { version = "0.2", default-features = false }
